package tests
package tests



























































































}	}		t.Fatalf("new thought id = %d, want 3", idNew)	if idNew != 3 {	}		t.Fatalf("create thought d: %v", err)	if err != nil {	idNew, err := st.CreateThought("d")	// New inserts should continue at max(id)+1.	}		t.Fatalf("expected thought 3 to be missing after reindex")	if _, _, err := st.GetThought(3); err == nil {	}		t.Fatalf("thought 2 events missing after reindex")	if len(ev2) == 0 {	}		t.Fatalf("thought 2 content = %q, want %q", th2.Content, "c")	if th2.Content != "c" {	}		t.Fatalf("get thought 2: %v", err)	if err != nil {	th2, ev2, err := st.GetThought(2)	}		t.Fatalf("thought 1 events missing after reindex")	if len(ev1) == 0 {	}		t.Fatalf("thought 1 content = %q, want %q", th1.Content, "a")	if th1.Content != "a" {	}		t.Fatalf("get thought 1: %v", err)	if err != nil {	th1, ev1, err := st.GetThought(1)	// IDs should be dense again: old 1 stays 1, old 3 becomes 2.	}		t.Fatalf("reindex thought ids: %v", err)	if err := st.ReindexThoughtIDs(); err != nil {	}		t.Fatalf("release thought: %v", err)	if err := st.ReleaseThought(id2); err != nil {	// Delete the middle thought to create a gap.	}		t.Fatalf("append event c: %v", err)	if err := st.AppendEvent(id3, "evt", nil, nil, nil); err != nil {	}		t.Fatalf("append event b: %v", err)	if err := st.AppendEvent(id2, "evt", nil, nil, nil); err != nil {	}		t.Fatalf("append event a: %v", err)	if err := st.AppendEvent(id1, "evt", nil, nil, nil); err != nil {	}		t.Fatalf("create thought c: %v", err)	if err != nil {	id3, err := st.CreateThought("c")	}		t.Fatalf("create thought b: %v", err)	if err != nil {	id2, err := st.CreateThought("b")	}		t.Fatalf("create thought a: %v", err)	if err != nil {	id1, err := st.CreateThought("a")	}		t.Fatalf("new store: %v", err)	if err != nil {	st, err := storage.New(db)	t.Cleanup(func() { _ = db.Close() })	}		t.Fatalf("open: %v", err)	if err != nil {	db, err := storage.Open(dbPath)	dbPath := filepath.Join(t.TempDir(), "peony.db")func TestStore_ReindexThoughtIDs(t *testing.T) {// TestStore_ReindexThoughtIDs verifies renumbering thoughts.id updates events.thought_id.)	"github.com/ri5hii/peony/internal/storage"	"testing"	"path/filepath"import (